(defparameter tester 0)
(defparameter catcher 0)
(defparameter init 0)
(setf tester 87)
(setf catcher (sqrt tester))
(defparameter llst'())
(loop for x from 2
  while(<= x catcher)
  do (push x llst)
)
(defparameter breaker 0)
(dolist(x llst)
  (if(= 0 (mod tester x))
    (setf breaker 1)
  )
)
(if (= breaker 1) (print 'is_not_a_prime)(print 'is_a_prime))
(format t "~%")
